apiVersion: apps/v1             # Versión de kubernetes
kind: Deployment                # Tipo de Objeto 
metadata:                       
  name: node-deployment        
  labels:                             
    app: node-app               # Etiqueta para el despliegue
spec:                           
  replicas: 1                   # Número de replicas que tendrá este pod
  selector:                     
    matchLabels:              
      app: node-app             # Etiqueta para que otros objetos de kubernetes lo encuentren
  template:                     # Es la configuración final del pod 
    metadata:                   
      labels:                   
        app: node-app         
    spec:                       
      containers:               
      - name: node-app          # Nombre del contenedor
        image: gcr.io/labkubernetes-437921/kubernetesexample      
        ports:                  
        - containerPort: 8080   
